In [58]:
import numpy as np

In [59]:
arr = np.arange(25)




In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
ranarr = np.random.randint(0, 50, 10)

In [62]:
ranarr

array([43, 25,  9, 30, 45, 39, 12,  7, 33, 36], dtype=int32)

In [63]:
arr.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
ranarr

array([43, 25,  9, 30, 45, 39, 12,  7, 33, 36], dtype=int32)

In [65]:
ranarr.max()


np.int32(45)

In [66]:
ranarr.min()

np.int32(7)

In [67]:
ranarr.argmax()

np.int64(4)

In [68]:
ranarr.argmin()

np.int64(7)

In [69]:
arr.shape


(25,)

In [70]:
arr.shape

(25,)

In [71]:
arr = arr.reshape(5,5)

In [72]:
arr.shape

(5, 5)

In [73]:
arr.dtype

dtype('int64')

In [74]:
arr = np.arange(0, 11)

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr[8]

np.int64(8)

In [77]:
arr[1:5]

array([1, 2, 3, 4])

In [78]:
arr[-1]



np.int64(10)

In [79]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [80]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [81]:
arr[0:5] = 100


In [82]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [83]:
arr = np.arange(0,11)


In [84]:
slice_of_arr = arr[0:6]

In [85]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [86]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [91]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [92]:
arr_2d[0][0]


np.int64(5)

In [93]:
arr_2d[0]

array([ 5, 10, 15])

In [94]:
arr_2d[1][1]

np.int64(25)

In [95]:
arr_2d[1][2]

np.int64(30)

In [97]:
arr_2d[2][1]

np.int64(40)

In [98]:
arr_2d[2,1]


np.int64(40)

In [99]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [100]:
arr_2d[:1,:2]

array([[ 5, 10]])

In [101]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [102]:
 arr_2d[1:2,:3]

array([[20, 25, 30]])

In [103]:
arr = np.arange(1,11)

In [104]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [106]:
bool_array = arr > 5

In [107]:
arr[bool_array]

array([ 6,  7,  8,  9, 10])

In [108]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [109]:
arr[arr<3]


array([1, 2])

In [110]:
arr_2d = np.arange(50).reshape(5,10)

In [111]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [116]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [117]:
arr = np.arange(0,11)

In [118]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [120]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [122]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [123]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [124]:
arr ** 3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [125]:
1/0

ZeroDivisionError: division by zero

In [126]:
arr / arr

C:\Users\AaronMathis\AppData\Local\Temp\ipykernel_15300\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [127]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [128]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [129]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [130]:
np.max(arr)

np.int64(10)

In [131]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [132]:
np.log(arr)

C:\Users\AaronMathis\AppData\Local\Temp\ipykernel_15300\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])